#!/usr/bin/env python3

"""Plot Figure 6 sweeps from the CSV generated by `reproduce_fig6`.

The script is intentionally lightweight:
- reads the project CSV with the standard library;
- uses matplotlib only for rendering;
- keeps all figure generation outside the C++ executables.
"""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import colorsys
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

X_TICKS = [0.0, 0.4, 0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6, 4.0]
DEFAULT_Y_MAX = 1.2
PANEL_Y_MAX_OVERRIDES = {
    "SG-006c": 1.0,
    "SG-006e": 1.0,
}

REQUIRED_COLUMNS = {
    "panel_id",
    "curve_id",
    "mode_family",
    "p",
    "q",
    "b_over_A4",
    "kz_normalized_against_n4",
}

DEFAULT_SOLVER_MODEL = "closed_form"
DEFAULT_VARIANT_ID = "default"
DEFAULT_GEOMETRY_MODEL = "rectangular"


@dataclass(frozen=True)
class CurvePoint:
    panel_id: str
    curve_id: str
    solver_model: str
    variant_id: str
    mode_family: str
    geometry_model: str
    p: int
    q: int
    b_over_A4: float
    kz_normalized_against_n4: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot a Figure 6 panel from a CSV generated by reproduce_fig6."
    )
    parser.add_argument(
        "input_csv",
        help="CSV file generated by reproduce_fig6.",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output image path. Defaults to the CSV path with .png extension.",
    )
    parser.add_argument(
        "--panel-title",
        help="Optional title override. Defaults to the panel_id stored in the CSV.",
    )
    parser.add_argument(
        "--y-max",
        type=float,
        help="Optional y-axis upper bound override. By default the script uses panel-specific limits.",
    )
    return parser.parse_args()


def panel_y_max(panel_id: str) -> float:
    return PANEL_Y_MAX_OVERRIDES.get(panel_id, DEFAULT_Y_MAX)


def y_ticks_for_limit(y_max: float) -> list[float]:
    step = 0.2
    tick_count = int(round(y_max / step))
    return [round(step * index, 1) for index in range(tick_count + 1)]


def mode_label(point: CurvePoint) -> str:
    superscript = "y" if point.mode_family == "E_y" else "x"
    indices = f"0{point.q}" if point.geometry_model == "slab" else f"{point.p}{point.q}"
    return rf"$E^{{{superscript}}}_{{{indices}}}$"


def curve_sort_key(point: CurvePoint) -> tuple[int, int, int, int]:
    family_order = 0 if point.mode_family == "E_y" else 1
    solver_order = 0 if point.solver_model == "exact" else 1
    return (point.p, point.q, family_order, solver_order)


def parse_required_float(row: dict[str, str], field_name: str) -> float:
    try:
        value = float(row[field_name])
    except KeyError as exc:
        raise ValueError(f"Missing required column: {field_name}") from exc
    except ValueError as exc:
        raise ValueError(f"Invalid float value in column '{field_name}': {row.get(field_name)!r}") from exc
    return value


def parse_required_int(row: dict[str, str], field_name: str) -> int:
    try:
        value = int(row[field_name])
    except KeyError as exc:
        raise ValueError(f"Missing required column: {field_name}") from exc
    except ValueError as exc:
        raise ValueError(f"Invalid integer value in column '{field_name}': {row.get(field_name)!r}") from exc
    return value


def validate_columns(fieldnames: list[str] | None) -> None:
    if not fieldnames:
        raise ValueError("CSV file is empty or missing a header row.")

    missing = REQUIRED_COLUMNS.difference(fieldnames)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"CSV is missing required columns: {missing_text}")


def parse_curve_point(row: dict[str, str]) -> CurvePoint | None:
    y_value = parse_required_float(row, "kz_normalized_against_n4")
    if math.isnan(y_value) or y_value < 0.0:
        return None

    return CurvePoint(
        panel_id=row["panel_id"],
        curve_id=row["curve_id"],
        solver_model=row.get("solver_model", DEFAULT_SOLVER_MODEL),
        variant_id=row.get("variant_id", DEFAULT_VARIANT_ID),
        mode_family=row["mode_family"],
        geometry_model=row.get("geometry_model", DEFAULT_GEOMETRY_MODEL),
        p=parse_required_int(row, "p"),
        q=parse_required_int(row, "q"),
        b_over_A4=parse_required_float(row, "b_over_A4"),
        kz_normalized_against_n4=y_value,
    )


def load_curves(csv_path: Path) -> tuple[str, dict[tuple[str, str, str], list[CurvePoint]]]:
    grouped_rows: dict[tuple[str, str, str], list[CurvePoint]] = defaultdict(list)
    panel_id = ""

    if not csv_path.is_file():
        raise FileNotFoundError(f"Input CSV not found: {csv_path}")

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        validate_columns(reader.fieldnames)

        for row in reader:
            point = parse_curve_point(row)
            if point is None:
                continue

            panel_id = point.panel_id
            key = (point.curve_id, point.solver_model, point.variant_id)
            grouped_rows[key].append(point)

    for rows in grouped_rows.values():
        rows.sort(key=lambda point: point.b_over_A4)

    return panel_id, grouped_rows


def adjust_color(
    color: tuple[float, float, float, float],
    lightness_delta: float,
) -> tuple[float, float, float, float]:
    red, green, blue, alpha = color
    hue, lightness, saturation = colorsys.rgb_to_hls(red, green, blue)
    shifted_lightness = max(0.0, min(1.0, lightness + lightness_delta))
    shifted_red, shifted_green, shifted_blue = colorsys.hls_to_rgb(
        hue,
        shifted_lightness,
        saturation,
    )
    return (shifted_red, shifted_green, shifted_blue, alpha)


def build_variant_lightness(variant_ids: list[str]) -> dict[str, float]:
    if not variant_ids:
        return {}

    if len(variant_ids) == 1:
        return {variant_ids[0]: 0.0}

    center = (len(variant_ids) - 1) / 2.0
    step = 0.18
    return {
        variant_id: (index - center) * step
        for index, variant_id in enumerate(variant_ids)
    }


def build_plot(
    panel_id: str,
    grouped_rows: dict[tuple[str, str, str], list[CurvePoint]],
    output_path: Path,
    title: str,
    y_max_override: float | None,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    figure, axis = plt.subplots(figsize=(9.0, 6.0))

    sorted_curves = sorted(
        grouped_rows.values(),
        key=lambda rows: curve_sort_key(rows[0]),
    )

    base_curve_ids = sorted({rows[0].curve_id for rows in sorted_curves})
    tab10 = plt.colormaps["tab10"]
    color_map = {
        curve_id: tab10(index % 10)
        for index, curve_id in enumerate(base_curve_ids)
    }

    variant_ids = sorted({rows[0].variant_id for rows in sorted_curves})
    variant_lightness = build_variant_lightness(variant_ids)

    solver_models_present = sorted({rows[0].solver_model for rows in sorted_curves})
    mode_legend_handles: list[Line2D] = []
    variant_legend_handles: list[Line2D] = []
    seen_curve_ids: set[str] = set()
    seen_variant_ids: set[str] = set()

    for rows in sorted_curves:
        if not rows:
            continue

        first = rows[0]
        linestyle = "-" if first.solver_model == "exact" else "--"
        linewidth = 2.0 if first.p == 1 and first.q == 1 else 1.4
        line_color = adjust_color(
            color_map[first.curve_id],
            variant_lightness.get(first.variant_id, 0.0),
        )

        x_values = [point.b_over_A4 for point in rows]
        y_values = [point.kz_normalized_against_n4 for point in rows]

        axis.plot(
            x_values,
            y_values,
            color=line_color,
            linestyle=linestyle,
            linewidth=linewidth,
        )

        if first.curve_id not in seen_curve_ids:
            seen_curve_ids.add(first.curve_id)
            mode_legend_handles.append(
                Line2D(
                    [0],
                    [0],
                    color=color_map[first.curve_id],
                    linestyle="-",
                    linewidth=2.0,
                    label=mode_label(first),
                )
            )

        if first.variant_id not in seen_variant_ids and first.variant_id != DEFAULT_VARIANT_ID:
            seen_variant_ids.add(first.variant_id)
            variant_legend_handles.append(
                Line2D(
                    [0],
                    [0],
                    color=adjust_color(
                        (0.2, 0.2, 0.2, 1.0),
                        variant_lightness.get(first.variant_id, 0.0),
                    ),
                    linestyle="-",
                    linewidth=2.0,
                    label=first.variant_id,
                )
            )

    y_max = y_max_override if y_max_override is not None else panel_y_max(panel_id)
    if y_max <= 0.0:
        raise ValueError("y-axis upper bound must be positive.")

    axis.set_xlim(0.0, 4.0)
    axis.set_ylim(0.0, y_max)
    axis.set_xticks(X_TICKS)
    axis.set_yticks(y_ticks_for_limit(y_max))
    axis.set_xlabel(r"$b / A_4$")
    axis.set_ylabel(r"$(k_z^2-k_4^2)/(k_1^2-k_4^2)$")
    axis.set_title(title or panel_id)
    axis.grid(True, which="major", color="#d0d0d0", linewidth=0.8)

    if mode_legend_handles:
        mode_legend = axis.legend(
            handles=mode_legend_handles,
            loc="upper left",
            ncol=2,
            frameon=True,
            title="Modes",
        )
        axis.add_artist(mode_legend)

    if variant_legend_handles:
        variant_legend = axis.legend(
            handles=variant_legend_handles,
            loc="upper right",
            frameon=True,
            title="Materials",
        )
        axis.add_artist(variant_legend)

    if len(solver_models_present) > 1:
        solver_handles = [
            Line2D([0], [0], color="black", linestyle="-", linewidth=2.0, label="exact"),
            Line2D([0], [0], color="black", linestyle="--", linewidth=2.0, label="closed_form"),
        ]
        axis.legend(
            handles=solver_handles,
            loc="lower right",
            frameon=True,
            title="Solvers",
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    input_csv = Path(args.input_csv)
    output_path = Path(args.output) if args.output else input_csv.with_suffix(".png")

    panel_id, grouped_rows = load_curves(input_csv)
    if not grouped_rows:
        raise SystemExit("No plottable rows were found in the CSV.")

    build_plot(
        panel_id=panel_id,
        grouped_rows=grouped_rows,
        output_path=output_path,
        title=args.panel_title or panel_id,
        y_max_override=args.y_max,
    )

    print(f"Wrote plot to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
