#!/usr/bin/env python3

"""Plot Figure 10 sweeps from the CSV generated by `reproduce_fig10`."""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

REQUIRED_COLUMNS = {
    "case_id",
    "curve_id",
    "solver_model",
    "a_over_A5",
    "c_over_a",
    "normalized_coupling",
    "curve_label",
}


@dataclass(frozen=True)
class CurvePoint:
    case_id: str
    curve_id: str
    solver_model: str
    a_over_A5: float
    c_over_a: float
    normalized_coupling: float
    curve_label: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the Figure 10 reproduction from a CSV generated by reproduce_fig10."
    )
    parser.add_argument("input_csv", type=Path, help="CSV file generated by reproduce_fig10.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output image path. Defaults to the CSV path with .png extension.",
    )
    parser.add_argument("--title", help="Optional title override.")
    parser.add_argument(
        "--no-title",
        action="store_true",
        help="Suppress the default case title. Useful for article-style comparisons.",
    )
    return parser.parse_args()


def validate_columns(fieldnames: list[str] | None) -> None:
    if not fieldnames:
        raise ValueError("CSV file is empty or missing a header row.")

    missing = REQUIRED_COLUMNS.difference(fieldnames)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"CSV is missing required columns: {missing_text}")


def parse_curve_point(row: dict[str, str]) -> CurvePoint | None:
    y_value = float(row["normalized_coupling"])
    if math.isnan(y_value) or y_value <= 0.0:
        return None

    return CurvePoint(
        case_id=row["case_id"],
        curve_id=row["curve_id"],
        solver_model=row["solver_model"],
        a_over_A5=float(row["a_over_A5"]),
        c_over_a=float(row["c_over_a"]),
        normalized_coupling=y_value,
        curve_label=row["curve_label"],
    )


def load_curves(csv_path: Path) -> tuple[str, dict[tuple[str, str], list[CurvePoint]]]:
    if not csv_path.is_file():
        raise FileNotFoundError(f"Input CSV not found: {csv_path}")

    grouped: dict[tuple[str, str], list[CurvePoint]] = defaultdict(list)
    case_id = ""

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        validate_columns(reader.fieldnames)

        for row in reader:
            point = parse_curve_point(row)
            if point is None:
                continue

            case_id = point.case_id
            grouped[(point.curve_id, point.solver_model)].append(point)

    for rows in grouped.values():
        rows.sort(key=lambda point: point.c_over_a)

    return case_id, grouped


def curve_sort_key(rows: list[CurvePoint]) -> float:
    return rows[0].a_over_A5


def label_anchor(rows: list[CurvePoint]) -> CurvePoint:
    if not rows:
        raise ValueError("Cannot select label anchor from an empty curve.")

    parameter = rows[0].a_over_A5
    if parameter <= 0.75:
        anchor_index = min(len(rows) - 1, max(0, len(rows) * 4 // 5))
    elif parameter <= 1.5:
        anchor_index = min(len(rows) - 1, max(0, len(rows) * 2 // 3))
    else:
        anchor_index = min(len(rows) - 1, max(0, len(rows) * 2 // 5))

    return rows[anchor_index]


def build_plot(
    case_id: str,
    grouped_curves: dict[tuple[str, str], list[CurvePoint]],
    output_path: Path,
    title: str | None,
    show_default_title: bool,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    figure, axis = plt.subplots(figsize=(8.6, 7.8))

    sorted_groups = sorted(grouped_curves.values(), key=curve_sort_key)
    label_rows_by_curve: dict[str, CurvePoint] = {}

    for rows in sorted_groups:
        if not rows:
            continue

        first = rows[0]
        x_values = [point.c_over_a for point in rows]
        y_values = [point.normalized_coupling for point in rows]

        axis.semilogy(
            x_values,
            y_values,
            color="black",
            linestyle="-" if first.solver_model == "exact" else "--",
            linewidth=1.8,
        )

        if first.solver_model == "exact":
            label_rows_by_curve[first.curve_id] = label_anchor(rows)
        elif first.curve_id not in label_rows_by_curve:
            label_rows_by_curve[first.curve_id] = label_anchor(rows)

    for point in label_rows_by_curve.values():
        axis.text(
            point.c_over_a + 0.03,
            point.normalized_coupling * 1.05,
            point.curve_label,
            fontsize=10,
        )

    axis.set_xlim(0.0, 3.0)
    axis.set_ylim(1.0e-4, 10.0)
    axis.set_xticks([index / 2 for index in range(7)])
    axis.set_xlabel(r"$c/a$")
    axis.set_ylabel(
        r"$|K|a/\left(\left[1-\left(n_5/n_1\right)^2\right]^{1/2}k_z\right)$"
    )

    if title is not None:
        axis.set_title(title)
    elif show_default_title:
        axis.set_title(case_id)

    axis.grid(True, which="major", color="#c8c8c8", linewidth=0.8)
    axis.grid(True, which="minor", color="#e6e6e6", linewidth=0.5, alpha=0.6)

    parameter_handle = Line2D(
        [0],
        [0],
        color="black",
        linestyle="none",
        label=r"Labels: $a/A_5 = \frac{2a}{\lambda}\,(n_1^2-n_5^2)^{1/2}$",
    )
    solver_handles = [
        Line2D([0], [0], color="black", linestyle="-", linewidth=1.8, label="exact"),
        Line2D([0], [0], color="black", linestyle="--", linewidth=1.8, label="closed_form"),
        parameter_handle,
    ]
    axis.legend(handles=solver_handles, loc="lower left", frameon=True, title="Curves")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    output_path = args.output if args.output else args.input_csv.with_suffix(".png")

    case_id, grouped_curves = load_curves(args.input_csv)
    if not grouped_curves:
        raise SystemExit("No plottable rows were found in the CSV.")

    build_plot(
        case_id=case_id,
        grouped_curves=grouped_curves,
        output_path=output_path,
        title=args.title,
        show_default_title=not args.no_title,
    )

    print(f"Wrote plot to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
