#!/usr/bin/env python3

"""Plot Figure 10 sweeps from the CSV generated by `reproduce_fig10`."""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

from mode_colors import SOLVER_LINESTYLE, sweep_color

REQUIRED_COLUMNS = {
    "case_id",
    "curve_id",
    "solver_model",
    "a_over_A5",
    "c_over_a",
    "normalized_coupling",
    "curve_label",
}


@dataclass(frozen=True)
class CurvePoint:
    case_id: str
    curve_id: str
    solver_model: str
    a_over_A5: float
    c_over_a: float
    normalized_coupling: float
    curve_label: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the Figure 10 reproduction from a CSV generated by reproduce_fig10."
    )
    parser.add_argument("input_csv", type=Path, help="CSV file generated by reproduce_fig10.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output image path. Defaults to the CSV path with .png extension.",
    )
    parser.add_argument("--title", help="Optional title override.")
    parser.add_argument(
        "--no-title",
        action="store_true",
        help="Suppress the default case title. Useful for article-style comparisons.",
    )
    return parser.parse_args()


def validate_columns(fieldnames: list[str] | None) -> None:
    if not fieldnames:
        raise ValueError("CSV file is empty or missing a header row.")

    missing = REQUIRED_COLUMNS.difference(fieldnames)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"CSV is missing required columns: {missing_text}")


def parse_curve_point(row: dict[str, str]) -> CurvePoint | None:
    y_value = float(row["normalized_coupling"])
    if math.isnan(y_value) or y_value <= 0.0:
        return None

    return CurvePoint(
        case_id=row["case_id"],
        curve_id=row["curve_id"],
        solver_model=row["solver_model"],
        a_over_A5=float(row["a_over_A5"]),
        c_over_a=float(row["c_over_a"]),
        normalized_coupling=y_value,
        curve_label=row["curve_label"],
    )


def load_curves(csv_path: Path) -> tuple[str, dict[tuple[str, str], list[CurvePoint]]]:
    if not csv_path.is_file():
        raise FileNotFoundError(f"Input CSV not found: {csv_path}")

    grouped: dict[tuple[str, str], list[CurvePoint]] = defaultdict(list)
    case_id = ""

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        validate_columns(reader.fieldnames)

        for row in reader:
            point = parse_curve_point(row)
            if point is None:
                continue

            case_id = point.case_id
            grouped[(point.curve_id, point.solver_model)].append(point)

    for rows in grouped.values():
        rows.sort(key=lambda point: point.c_over_a)

    return case_id, grouped


def curve_sort_key(rows: list[CurvePoint]) -> float:
    return rows[0].a_over_A5


def curve_label_legend_text(curve_labels: list[str]) -> str:
    if len(curve_labels) <= 4:
        return "a/A5 = " + ", ".join(curve_labels)

    head = ", ".join(curve_labels[:4])
    tail = ", ".join(curve_labels[4:])
    return "a/A5 = " + head + ",\n" + "       " + tail


def build_plot(
    case_id: str,
    grouped_curves: dict[tuple[str, str], list[CurvePoint]],
    output_path: Path,
    title: str | None,
    show_default_title: bool,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    figure, axis = plt.subplots(figsize=(8.2, 8.2))
    axis.set_box_aspect(1.0)

    sorted_groups = sorted(grouped_curves.values(), key=curve_sort_key)
    curve_labels = sorted({rows[0].curve_label for rows in sorted_groups}, key=float)

    # Assign a fixed color per unique a/A5 value (same color for both solvers).
    unique_labels = sorted({rows[0].curve_label for rows in sorted_groups}, key=float)
    label_to_color = {label: sweep_color(idx) for idx, label in enumerate(unique_labels)}

    for rows in sorted_groups:
        if not rows:
            continue

        first = rows[0]
        x_values = [point.c_over_a for point in rows]
        y_values = [point.normalized_coupling for point in rows]

        axis.semilogy(
            x_values,
            y_values,
            color=label_to_color[first.curve_label],
            linestyle=SOLVER_LINESTYLE.get(first.solver_model, "-"),
            linewidth=1.8,
        )

    axis.set_xlim(0.0, 3.0)
    axis.set_ylim(1.0e-4, 10.0)
    axis.set_xticks([index / 2 for index in range(7)])
    axis.set_xlabel(r"$c/a$")
    axis.set_ylabel(
        r"$|K|a/\left(\left[1-\left(n_5/n_1\right)^2\right]^{1/2}k_z\right)$"
    )

    if title is not None:
        axis.set_title(title)
    elif show_default_title:
        axis.set_title(case_id)

    axis.grid(True, which="major", color="#c8c8c8", linewidth=0.8)
    axis.grid(True, which="minor", color="#e6e6e6", linewidth=0.5, alpha=0.6)

    solver_models_present = sorted({rows[0].solver_model for rows in sorted_groups})
    solver_handles = [
        Line2D(
            [0], [0],
            color="black",
            linestyle=SOLVER_LINESTYLE.get(sm, "-"),
            linewidth=1.8,
            label=sm,
        )
        for sm in solver_models_present
    ]

    color_handles = [
        Line2D(
            [0], [0],
            color=label_to_color[label],
            linestyle="-",
            linewidth=1.8,
            label=f"a/A5 = {label}",
        )
        for label in unique_labels
    ]

    axis.legend(
        handles=solver_handles + color_handles,
        loc="upper right",
        frameon=True,
        framealpha=0.95,
        title="Curvas",
        fontsize=9,
        title_fontsize=10,
        labelspacing=0.4,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    output_path = args.output if args.output else args.input_csv.with_suffix(".png")

    case_id, grouped_curves = load_curves(args.input_csv)
    if not grouped_curves:
        raise SystemExit("No plottable rows were found in the CSV.")

    build_plot(
        case_id=case_id,
        grouped_curves=grouped_curves,
        output_path=output_path,
        title=args.title,
        show_default_title=not args.no_title,
    )

    print(f"Wrote plot to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
