#!/usr/bin/env python3

"""Plot Figure 8 sweeps from the CSV generated by `reproduce_fig8`."""

from __future__ import annotations

import argparse
import csv
import math
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

X_TICKS = [0.0, 0.4, 0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6, 4.0]
Y_TICKS = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]

REQUIRED_COLUMNS = {
    "case_id",
    "curve_id",
    "solver_model",
    "mode_family",
    "p",
    "q",
    "a_over_A",
    "kz_normalized_against_n4",
}


@dataclass(frozen=True)
class CurvePoint:
    case_id: str
    curve_id: str
    solver_model: str
    mode_family: str
    p: int
    q: int
    a_over_A: float
    kz_normalized_against_n4: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the Figure 8 reproduction from a CSV generated by reproduce_fig8."
    )
    parser.add_argument("input_csv", type=Path, help="CSV file generated by reproduce_fig8.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output image path. Defaults to the CSV path with .png extension.",
    )
    parser.add_argument("--title", help="Optional title override.")
    parser.add_argument(
        "--no-title",
        action="store_true",
        help="Suppress the default case title. Useful for article-style comparisons.",
    )
    return parser.parse_args()


def validate_columns(fieldnames: list[str] | None) -> None:
    if not fieldnames:
        raise ValueError("CSV file is empty or missing a header row.")

    missing = REQUIRED_COLUMNS.difference(fieldnames)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"CSV is missing required columns: {missing_text}")


def mode_label(point: CurvePoint) -> str:
    superscript = "y" if point.mode_family == "E_y" else "x"
    return rf"$E^{{{superscript}}}_{{{point.p}{point.q}}}$"


def curve_sort_key(rows: list[CurvePoint]) -> tuple[int, int, int]:
    family_order = 0 if rows[0].mode_family == "E_y" else 1
    return (rows[0].p, rows[0].q, family_order)


def parse_curve_point(row: dict[str, str]) -> CurvePoint | None:
    y_value = float(row["kz_normalized_against_n4"])
    if math.isnan(y_value) or y_value < 0.0 or y_value > 1.0:
        return None

    return CurvePoint(
        case_id=row["case_id"],
        curve_id=row["curve_id"],
        solver_model=row["solver_model"],
        mode_family=row["mode_family"],
        p=int(row["p"]),
        q=int(row["q"]),
        a_over_A=float(row["a_over_A"]),
        kz_normalized_against_n4=y_value,
    )


def load_curves(csv_path: Path) -> tuple[str, dict[tuple[str, str], list[CurvePoint]]]:
    if not csv_path.is_file():
        raise FileNotFoundError(f"Input CSV not found: {csv_path}")

    grouped: dict[tuple[str, str], list[CurvePoint]] = defaultdict(list)
    case_id = ""

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        validate_columns(reader.fieldnames)

        for row in reader:
            point = parse_curve_point(row)
            if point is None:
                continue

            case_id = point.case_id
            grouped[(point.curve_id, point.solver_model)].append(point)

    for rows in grouped.values():
        rows.sort(key=lambda point: point.a_over_A)

    return case_id, grouped


def label_anchor(rows: list[CurvePoint]) -> CurvePoint:
    if not rows:
        raise ValueError("Cannot select label anchor from an empty curve.")
    anchor_index = min(len(rows) - 1, max(0, len(rows) * 4 // 5))
    return rows[anchor_index]


def build_plot(
    case_id: str,
    grouped_curves: dict[tuple[str, str], list[CurvePoint]],
    output_path: Path,
    title: str | None,
    show_default_title: bool,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    figure, axis = plt.subplots(figsize=(9.0, 6.0))

    sorted_groups = sorted(grouped_curves.values(), key=curve_sort_key)
    base_curve_ids = sorted({rows[0].curve_id for rows in sorted_groups})

    color_map = {curve_id: "black" for curve_id in base_curve_ids}
    label_rows_by_curve: dict[str, CurvePoint] = {}

    for rows in sorted_groups:
        if not rows:
            continue

        first = rows[0]
        x_values = [point.a_over_A for point in rows]
        y_values = [point.kz_normalized_against_n4 for point in rows]

        axis.plot(
            x_values,
            y_values,
            color=color_map[first.curve_id],
            linestyle="-" if first.solver_model == "exact" else "--",
            linewidth=2.0 if first.p == 1 else 1.7,
        )

        if first.solver_model == "exact":
            label_rows_by_curve[first.curve_id] = label_anchor(rows)
        elif first.curve_id not in label_rows_by_curve:
            label_rows_by_curve[first.curve_id] = label_anchor(rows)

    for curve_id in base_curve_ids:
        point = label_rows_by_curve.get(curve_id)
        if point is None:
            continue

        x_value = min(3.82, point.a_over_A + 0.08)
        y_value = point.kz_normalized_against_n4 + 0.02
        axis.text(x_value, y_value, mode_label(point), fontsize=11)

    axis.set_xlim(0.0, 4.0)
    axis.set_ylim(0.0, 1.0)
    axis.set_xticks(X_TICKS)
    axis.set_yticks(Y_TICKS)
    axis.set_xlabel(r"$a/A = \frac{2a}{\lambda}\left(n_1^2-n_4^2\right)^{1/2}$")
    axis.set_ylabel(r"$(k_z^2-k_4^2)/(k_1^2-k_4^2)$")

    if title is not None:
        axis.set_title(title)
    elif show_default_title:
        axis.set_title(case_id)

    axis.grid(True, which="major", color="#d0d0d0", linewidth=0.8)

    solver_handles = [
        Line2D([0], [0], color="black", linestyle="-", linewidth=2.0, label="exact"),
        Line2D([0], [0], color="black", linestyle="--", linewidth=2.0, label="closed_form"),
    ]
    axis.legend(handles=solver_handles, loc="lower right", frameon=True, title="Solvers")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    output_path = args.output if args.output else args.input_csv.with_suffix(".png")

    case_id, grouped_curves = load_curves(args.input_csv)
    if not grouped_curves:
        raise SystemExit("No plottable rows were found in the CSV.")

    build_plot(
        case_id=case_id,
        grouped_curves=grouped_curves,
        output_path=output_path,
        title=args.title,
        show_default_title=not args.no_title,
    )

    print(f"Wrote plot to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
