#!/usr/bin/env python3

"""Plot Figure 11 sweeps from the CSV generated by `reproduce_fig11`."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the Figure 11 reproduction from a CSV generated by reproduce_fig11."
    )
    parser.add_argument("input_csv", type=Path, help="CSV file generated by reproduce_fig11.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output image path. Defaults to the CSV path with .png extension.",
    )
    parser.add_argument("--title", help="Optional title override.")
    parser.add_argument(
        "--no-title",
        action="store_true",
        help="Suppress the default case title. Useful for article-style comparisons.",
    )
    return parser.parse_args()


def load_curves(csv_path: Path) -> tuple[str, dict[tuple[str, str, str], list[dict[str, str]]]]:
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = defaultdict(list)
    case_id = ""

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            case_id = row["case_id"]
            y_text = row["normalized_coupling"]
            if y_text == "nan":
                continue

            y_value = float(y_text)
            if y_value <= 0.0:
                continue

            grouped[(row["ratio_id"], row["curve_id"], row["solver_model"])].append(row)

    for rows in grouped.values():
        rows.sort(key=lambda row: float(row["c_over_a"]))

    return case_id, grouped


def curve_sort_key(rows: list[dict[str, str]]) -> tuple[float, float]:
    return (float(rows[0]["n1_over_n5"]), float(rows[0]["a_over_A5"]))


def label_anchor(rows: list[dict[str, str]]) -> dict[str, str]:
    parameter = float(rows[0]["a_over_A5"])
    if parameter <= 0.75:
        anchor_index = min(len(rows) - 1, max(0, len(rows) * 4 // 5))
    elif parameter <= 1.5:
        anchor_index = min(len(rows) - 1, max(0, len(rows) * 2 // 3))
    else:
        anchor_index = min(len(rows) - 1, max(0, len(rows) * 2 // 5))

    return rows[anchor_index]


def build_plot(
    case_id: str,
    grouped_curves: dict[tuple[str, str, str], list[dict[str, str]]],
    output_path: Path,
    title: str | None,
    show_default_title: bool,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    figure, axis = plt.subplots(figsize=(8.6, 7.8))

    sorted_groups = sorted(grouped_curves.values(), key=curve_sort_key)
    ratio_values = sorted({rows[0]["ratio_label"] for rows in sorted_groups}, key=float, reverse=True)
    ratio_styles = {
        ratio: style
        for ratio, style in zip(ratio_values, ["-", "-.", "--", ":"])
    }
    solver_colors = {
        "exact": "black",
        "closed_form": "#6e6e6e",
    }
    solver_labels = {
        "exact": "exact (black)",
        "closed_form": "closed_form (gray)",
    }
    label_rows_by_curve: dict[str, dict[str, str]] = {}
    preferred_ratio = ratio_values[0] if ratio_values else None

    for rows in sorted_groups:
        if not rows:
            continue

        solver_model = rows[0]["solver_model"]
        ratio_label = rows[0]["ratio_label"]
        x_values = [float(row["c_over_a"]) for row in rows]
        y_values = [float(row["normalized_coupling"]) for row in rows]

        axis.semilogy(
            x_values,
            y_values,
            color=solver_colors.get(solver_model, "black"),
            linestyle=ratio_styles.get(ratio_label, "-"),
            linewidth=1.8,
        )

        if solver_model == "exact" and ratio_label == preferred_ratio:
            label_rows_by_curve[rows[0]["curve_id"]] = label_anchor(rows)

    for row in label_rows_by_curve.values():
        x_value = float(row["c_over_a"]) + 0.03
        y_value = float(row["normalized_coupling"]) * 1.05
        axis.text(x_value, y_value, row["curve_label"], fontsize=10)

    axis.set_xlim(0.0, 3.0)
    axis.set_ylim(1.0e-4, 10.0)
    axis.set_xticks([index / 2 for index in range(7)])
    axis.set_xlabel(r"$c/a$")
    axis.set_ylabel(
        r"$|K|a/\left(\left[1-\left(n_5/n_1\right)^2\right]^{1/2}k_z\right)$"
    )
    if title is not None:
        axis.set_title(title)
    elif show_default_title:
        axis.set_title(case_id)

    axis.grid(True, which="major", color="#c8c8c8", linewidth=0.8)
    axis.grid(True, which="minor", color="#e6e6e6", linewidth=0.5, alpha=0.6)

    ratio_handles = [
        Line2D(
            [0],
            [0],
            color="black",
            linestyle=ratio_styles.get(ratio, "-"),
            linewidth=1.8,
            label=fr"$n_1/n_5 = {ratio}$",
        )
        for ratio in ratio_values
    ]
    solver_models_present = sorted({rows[0]["solver_model"] for rows in sorted_groups})
    solver_handles = [
        Line2D(
            [0],
            [0],
            color=solver_colors.get(solver_model, "black"),
            linestyle="-",
            linewidth=1.8,
            label=solver_labels.get(solver_model, solver_model),
        )
        for solver_model in solver_models_present
    ]
    parameter_handle = Line2D(
        [0],
        [0],
        color="black",
        linestyle="none",
        label=r"Labels: $a/A_5 = \frac{2a}{\lambda}\,(n_1^2-n_5^2)^{1/2}$",
    )
    handles = solver_handles + ratio_handles + [parameter_handle]
    axis.legend(handles=handles, loc="lower left", frameon=True, title="Curves")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    output_path = args.output if args.output else args.input_csv.with_suffix(".png")

    case_id, grouped_curves = load_curves(args.input_csv)
    if not grouped_curves:
        raise SystemExit("No plottable rows were found in the CSV.")

    build_plot(case_id, grouped_curves, output_path, args.title, not args.no_title)
    print(f"Wrote plot to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
