#!/usr/bin/env python3

"""Plot Figure 8 sweeps from the CSV generated by `reproduce_fig8`."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

X_TICKS = [0.0, 0.4, 0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6, 4.0]
Y_TICKS = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the Figure 8 reproduction from a CSV generated by reproduce_fig8."
    )
    parser.add_argument("input_csv", type=Path, help="CSV file generated by reproduce_fig8.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output image path. Defaults to the CSV path with .png extension.",
    )
    parser.add_argument("--title", help="Optional title override.")
    parser.add_argument(
        "--no-title",
        action="store_true",
        help="Suppress the default case title. Useful for article-style comparisons.",
    )
    return parser.parse_args()


def mode_label(row: dict[str, str]) -> str:
    superscript = "y" if row["mode_family"] == "E_y" else "x"
    return rf"$E^{{{superscript}}}_{{{row['p']}{row['q']}}}$"


def curve_sort_key(rows: list[dict[str, str]]) -> tuple[int, int, int]:
    family_order = 0 if rows[0]["mode_family"] == "E_y" else 1
    return (int(rows[0]["p"]), int(rows[0]["q"]), family_order)


def load_curves(csv_path: Path) -> tuple[str, dict[tuple[str, str], list[dict[str, str]]]]:
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    case_id = ""

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            case_id = row["case_id"]

            kz_normalized = row["kz_normalized_against_n4"]
            if kz_normalized == "nan":
                continue

            y_value = float(kz_normalized)
            if y_value < 0.0 or y_value > 1.0:
                continue

            grouped[(row["curve_id"], row["solver_model"])].append(row)

    for rows in grouped.values():
        rows.sort(key=lambda item: float(item["a_over_A"]))

    return case_id, grouped


def label_anchor(rows: list[dict[str, str]]) -> dict[str, str]:
    anchor_index = min(len(rows) - 1, max(0, len(rows) * 4 // 5))
    return rows[anchor_index]


def build_plot(
    case_id: str,
    grouped_curves: dict[tuple[str, str], list[dict[str, str]]],
    output_path: Path,
    title: str | None,
    show_default_title: bool,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    figure, axis = plt.subplots(figsize=(9.0, 6.0))

    sorted_groups = sorted(grouped_curves.values(), key=curve_sort_key)
    base_curve_ids = sorted({rows[0]["curve_id"] for rows in sorted_groups})
    color_map = {
        curve_id: "black"
        for curve_id in base_curve_ids
    }

    label_rows_by_curve: dict[str, dict[str, str]] = {}

    for rows in sorted_groups:
        if not rows:
            continue

        curve_id = rows[0]["curve_id"]
        solver_model = rows[0]["solver_model"]
        x_values = [float(row["a_over_A"]) for row in rows]
        y_values = [float(row["kz_normalized_against_n4"]) for row in rows]

        axis.plot(
            x_values,
            y_values,
            color=color_map[curve_id],
            linestyle="-" if solver_model == "exact" else "--",
            linewidth=2.0 if rows[0]["p"] == "1" else 1.7,
        )

        if solver_model == "exact":
            label_rows_by_curve[curve_id] = label_anchor(rows)
        elif curve_id not in label_rows_by_curve:
            label_rows_by_curve[curve_id] = label_anchor(rows)

    for curve_id in base_curve_ids:
        if curve_id not in label_rows_by_curve:
            continue

        row = label_rows_by_curve[curve_id]
        x_value = min(3.82, float(row["a_over_A"]) + 0.08)
        y_value = float(row["kz_normalized_against_n4"]) + 0.02
        axis.text(x_value, y_value, mode_label(row), fontsize=11)

    axis.set_xlim(0.0, 4.0)
    axis.set_ylim(0.0, 1.0)
    axis.set_xticks(X_TICKS)
    axis.set_yticks(Y_TICKS)
    axis.set_xlabel(r"$a/A = \frac{2a}{\lambda}\left(n_1^2-n_4^2\right)^{1/2}$")
    axis.set_ylabel(r"$(k_z^2-k_4^2)/(k_1^2-k_4^2)$")
    if title is not None:
        axis.set_title(title)
    elif show_default_title:
        axis.set_title(case_id)
    axis.grid(True, which="major", color="#d0d0d0", linewidth=0.8)

    solver_handles = [
        Line2D([0], [0], color="black", linestyle="-", linewidth=2.0, label="exact"),
        Line2D([0], [0], color="black", linestyle="--", linewidth=2.0, label="closed_form"),
    ]
    axis.legend(handles=solver_handles, loc="lower right", frameon=True, title="Solvers")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    output_path = args.output if args.output else args.input_csv.with_suffix(".png")

    case_id, grouped_curves = load_curves(args.input_csv)
    if not grouped_curves:
        raise SystemExit("No plottable rows were found in the CSV.")

    build_plot(case_id, grouped_curves, output_path, args.title, not args.no_title)
    print(f"Wrote plot to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
