#!/usr/bin/env python3

"""Plot Figure 6 sweeps from the CSV generated by `reproduce_fig6`.

The script is intentionally lightweight:
- reads the project CSV with the standard library;
- uses matplotlib only for rendering;
- keeps all figure generation outside the C++ executables.
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import colorsys
from matplotlib.lines import Line2D

X_TICKS = [0.0, 0.4, 0.8, 1.2, 1.6, 2.0, 2.4, 2.8, 3.2, 3.6, 4.0]
DEFAULT_Y_MAX = 1.2
PANEL_Y_MAX_OVERRIDES = {
    # Based on the current divergence report against the article scan.
    "SG-006c": 1.0,
    "SG-006e": 1.0,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot a Figure 6 panel from a CSV generated by reproduce_fig6."
    )
    parser.add_argument(
        "input_csv",
        help="CSV file generated by reproduce_fig6.",
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Output image path. Defaults to the CSV path with .png extension.",
    )
    parser.add_argument(
        "--panel-title",
        help="Optional title override. Defaults to the panel_id stored in the CSV.",
    )
    parser.add_argument(
        "--y-max",
        type=float,
        help="Optional y-axis upper bound override. By default the script uses panel-specific limits.",
    )
    return parser.parse_args()


def panel_y_max(panel_id: str) -> float:
    return PANEL_Y_MAX_OVERRIDES.get(panel_id, DEFAULT_Y_MAX)


def y_ticks_for_limit(y_max: float) -> list[float]:
    step = 0.2
    tick_count = int(round(y_max / step))
    return [round(step * index, 1) for index in range(tick_count + 1)]


def mode_label(row: dict[str, str]) -> str:
    family = row["mode_family"]
    superscript = "y" if family == "E_y" else "x"
    if row.get("geometry_model", "rectangular") == "slab":
        indices = f"0{row['q']}"
    else:
        indices = f"{row['p']}{row['q']}"
    return rf"$E^{{{superscript}}}_{{{indices}}}$"


def curve_sort_key(row: dict[str, str]) -> tuple[int, int, int, int]:
    family_order = 0 if row["mode_family"] == "E_y" else 1
    solver_order = 0 if row.get("solver_model", "closed_form") == "exact" else 1
    return (int(row["p"]), int(row["q"]), family_order, solver_order)


def load_curves(csv_path: Path) -> tuple[str, dict[tuple[str, str, str], list[dict[str, str]]]]:
    grouped_rows: dict[tuple[str, str, str], list[dict[str, str]]] = defaultdict(list)
    panel_id = ""

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            panel_id = row["panel_id"]

            kz_normalized = row["kz_normalized_against_n4"]
            if kz_normalized == "nan":
                continue

            y_value = float(kz_normalized)
            if y_value < 0.0:
                continue

            solver_model = row.get("solver_model", "closed_form")
            variant_id = row.get("variant_id", "default")
            grouped_rows[(row["curve_id"], solver_model, variant_id)].append(row)

    for rows in grouped_rows.values():
        rows.sort(key=lambda item: float(item["b_over_A4"]))

    return panel_id, grouped_rows


def adjust_color(color: tuple[float, float, float, float], lightness_delta: float) -> tuple[float, float, float, float]:
    red, green, blue, alpha = color
    hue, lightness, saturation = colorsys.rgb_to_hls(red, green, blue)
    shifted = max(0.0, min(1.0, lightness + lightness_delta))
    shifted_red, shifted_green, shifted_blue = colorsys.hls_to_rgb(hue, shifted, saturation)
    return (shifted_red, shifted_green, shifted_blue, alpha)


def build_plot(
    panel_id: str,
    grouped_rows: dict[tuple[str, str, str], list[dict[str, str]]],
    output_path: Path,
    title: str,
    y_max_override: float | None,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    figure, axis = plt.subplots(figsize=(9.0, 6.0))

    sorted_curves = sorted(
        grouped_rows.values(),
        key=lambda rows: curve_sort_key(rows[0]),
    )

    base_curve_ids = sorted({rows[0]["curve_id"] for rows in sorted_curves})
    color_map = {
        curve_id: plt.cm.tab10(index % 10)
        for index, curve_id in enumerate(base_curve_ids)
    }
    variant_ids = sorted({rows[0].get("variant_id", "default") for rows in sorted_curves})
    variant_lightness = {
        variant_id: (-0.18 + 0.18 * index)
        for index, variant_id in enumerate(variant_ids)
    }

    solver_models_present = sorted({rows[0].get("solver_model", "closed_form") for rows in sorted_curves})
    mode_legend_handles: list[Line2D] = []
    variant_legend_handles: list[Line2D] = []
    seen_curve_ids: set[str] = set()
    seen_variant_ids: set[str] = set()

    for rows in sorted_curves:
        if not rows:
            continue

        curve_id = rows[0]["curve_id"]
        solver_model = rows[0].get("solver_model", "closed_form")
        variant_id = rows[0].get("variant_id", "default")
        linestyle = "-" if solver_model == "exact" else "--"
        linewidth = 2.0 if rows[0]["p"] == "1" and rows[0]["q"] == "1" else 1.4
        line_color = adjust_color(
            color_map[curve_id],
            variant_lightness.get(variant_id, 0.0),
        )
        x_values = [float(row["b_over_A4"]) for row in rows]
        y_values = [float(row["kz_normalized_against_n4"]) for row in rows]

        axis.plot(
            x_values,
            y_values,
            color=line_color,
            linestyle=linestyle,
            linewidth=linewidth,
        )

        if curve_id not in seen_curve_ids:
            seen_curve_ids.add(curve_id)
            mode_legend_handles.append(
                Line2D(
                    [0],
                    [0],
                    color=color_map[curve_id],
                    linestyle="-",
                    linewidth=2.0,
                    label=mode_label(rows[0]),
                )
            )

        if variant_id not in seen_variant_ids and variant_id != "default":
            seen_variant_ids.add(variant_id)
            variant_legend_handles.append(
                Line2D(
                    [0],
                    [0],
                    color=adjust_color((0.2, 0.2, 0.2, 1.0), variant_lightness.get(variant_id, 0.0)),
                    linestyle="-",
                    linewidth=2.0,
                    label=variant_id,
                )
            )

    y_max = y_max_override if y_max_override is not None else panel_y_max(panel_id)
    if y_max <= 0.0:
        raise ValueError("y-axis upper bound must be positive.")

    axis.set_xlim(0.0, 4.0)
    axis.set_ylim(0.0, y_max)
    axis.set_xticks(X_TICKS)
    axis.set_yticks(y_ticks_for_limit(y_max))
    axis.set_xlabel(r"$b / A_4$")
    axis.set_ylabel(r"$(k_z^2-k_4^2)/(k_1^2-k_4^2)$")
    axis.set_title(title or panel_id)
    axis.grid(True, which="major", color="#d0d0d0", linewidth=0.8)

    if mode_legend_handles:
        mode_legend = axis.legend(
            handles=mode_legend_handles,
            loc="upper left",
            ncol=2,
            frameon=True,
            title="Modes",
        )
        axis.add_artist(mode_legend)

    if variant_legend_handles:
        variant_legend = axis.legend(
            handles=variant_legend_handles,
            loc="upper right",
            frameon=True,
            title="Materials",
        )
        axis.add_artist(variant_legend)

    if len(solver_models_present) > 1:
        solver_handles = [
            Line2D([0], [0], color="black", linestyle="-", linewidth=2.0, label="exact"),
            Line2D([0], [0], color="black", linestyle="--", linewidth=2.0, label="closed_form"),
        ]
        axis.legend(
            handles=solver_handles,
            loc="lower right",
            frameon=True,
            title="Solvers",
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    input_csv = Path(args.input_csv)
    output_path = Path(args.output) if args.output else input_csv.with_suffix(".png")

    panel_id, grouped_rows = load_curves(input_csv)
    if not grouped_rows:
        raise SystemExit("No plottable rows were found in the CSV.")

    build_plot(
        panel_id,
        grouped_rows,
        output_path,
        args.panel_title or panel_id,
        args.y_max,
    )
    print(f"Wrote plot to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
