#!/usr/bin/env python3

"""Render the calculated Table I as a formatted table in PNG and Markdown."""

from __future__ import annotations

import argparse
import csv
import math
from collections import OrderedDict
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt

REQUIRED_COLUMNS = {
    "case_id",
    "row_id",
    "article_panel_id",
    "solver_model",
    "a_over_b",
    "article_dimension_normalized",
    "computed_dimension_normalized",
    "relative_error",
}

SOLVER_COLUMNS = {
    "exact": ("Exact", "Err.ex [%]"),
    "closed_form": ("Closed", "Err.cl [%]"),
}


@dataclass(frozen=True)
class SummaryRow:
    case_id: str
    row_id: str
    article_panel_id: str
    solver_model: str
    a_over_b: float
    article_dimension_normalized: float
    computed_dimension_normalized: float
    relative_error: float


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render reproduce_table1.summary.csv as PNG and Markdown."
    )
    parser.add_argument("input_csv", type=Path, help="Summary CSV generated by reproduce_table1.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output PNG path. Defaults to the CSV path with .png extension.",
    )
    parser.add_argument(
        "--markdown-output",
        type=Path,
        help="Output Markdown path. Defaults to the CSV path with .md extension.",
    )
    parser.add_argument("--title", help="Optional title override.")
    parser.add_argument(
        "--no-title",
        action="store_true",
        help="Suppress the default title in the PNG and Markdown.",
    )
    return parser.parse_args()


def validate_columns(fieldnames: list[str] | None) -> None:
    if not fieldnames:
        raise ValueError("CSV file is empty or missing a header row.")

    missing = REQUIRED_COLUMNS.difference(fieldnames)
    if missing:
        missing_text = ", ".join(sorted(missing))
        raise ValueError(f"CSV is missing required columns: {missing_text}")


def parse_required_float(row: dict[str, str], field_name: str) -> float:
    try:
        return float(row[field_name])
    except KeyError as exc:
        raise ValueError(f"Missing required column: {field_name}") from exc
    except ValueError as exc:
        raise ValueError(f"Invalid float value in column '{field_name}': {row.get(field_name)!r}") from exc


def parse_row(row: dict[str, str]) -> SummaryRow | None:
    computed = parse_required_float(row, "computed_dimension_normalized")
    relative_error = parse_required_float(row, "relative_error")
    if math.isnan(computed) or math.isnan(relative_error):
        return None

    return SummaryRow(
        case_id=row["case_id"],
        row_id=row["row_id"],
        article_panel_id=row["article_panel_id"],
        solver_model=row["solver_model"],
        a_over_b=parse_required_float(row, "a_over_b"),
        article_dimension_normalized=parse_required_float(row, "article_dimension_normalized"),
        computed_dimension_normalized=computed,
        relative_error=relative_error,
    )


def load_rows(csv_path: Path) -> tuple[str, list[SummaryRow]]:
    if not csv_path.is_file():
        raise FileNotFoundError(f"Input CSV not found: {csv_path}")

    case_id = ""
    rows: list[SummaryRow] = []

    with csv_path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        validate_columns(reader.fieldnames)

        for raw_row in reader:
            row = parse_row(raw_row)
            if row is None:
                continue

            case_id = row.case_id
            rows.append(row)

    return case_id, rows


def compact_row_id(row_id: str) -> str:
    return row_id.removeprefix("SG-TBL-001")


def group_rows(rows: list[SummaryRow]) -> list[tuple[SummaryRow, dict[str, SummaryRow]]]:
    grouped: OrderedDict[str, list[SummaryRow]] = OrderedDict()
    for row in rows:
        grouped.setdefault(row.row_id, []).append(row)

    entries: list[tuple[SummaryRow, dict[str, SummaryRow]]] = []
    for group in grouped.values():
        reference_row = group[0]
        solver_rows = {row.solver_model: row for row in group}
        entries.append((reference_row, solver_rows))

    return entries


def format_value(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}f}"


def format_percent(value: float) -> str:
    return f"{100.0 * value:.2f}"


def build_table_matrix(
    entries: list[tuple[SummaryRow, dict[str, SummaryRow]]],
) -> tuple[list[str], list[list[str]], list[bool]]:
    headers = [
        "ID",
        "Panel",
        "a/b",
        "Article",
        "Exact",
        "Err.ex [%]",
        "Closed",
        "Err.cl [%]",
    ]
    numeric_columns = [False, False, True, True, True, True, True, True]

    rows: list[list[str]] = []
    for reference_row, solver_rows in entries:
        exact_row = solver_rows.get("exact")
        closed_row = solver_rows.get("closed_form")
        rows.append(
            [
                compact_row_id(reference_row.row_id),
                reference_row.article_panel_id,
                format_value(reference_row.a_over_b, 1),
                format_value(reference_row.article_dimension_normalized),
                format_value(exact_row.computed_dimension_normalized) if exact_row else "-",
                format_percent(exact_row.relative_error) if exact_row else "-",
                format_value(closed_row.computed_dimension_normalized) if closed_row else "-",
                format_percent(closed_row.relative_error) if closed_row else "-",
            ]
        )

    return headers, rows, numeric_columns


def build_ascii_table(
    headers: list[str],
    rows: list[list[str]],
    numeric_columns: list[bool],
) -> str:
    widths = [len(header) for header in headers]
    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], len(cell))

    border = "+" + "+".join("-" * (width + 2) for width in widths) + "+"

    def format_row(values: list[str]) -> str:
        cells: list[str] = []
        for index, value in enumerate(values):
            if numeric_columns[index]:
                cells.append(value.rjust(widths[index]))
            else:
                cells.append(value.ljust(widths[index]))
        return "| " + " | ".join(cells) + " |"

    lines = [border, format_row(headers), border]
    for row in rows:
        lines.append(format_row(row))
    lines.append(border)
    return "\n".join(lines)


def build_markdown_document(title: str | None, ascii_table: str) -> str:
    lines: list[str] = []
    if title:
        lines.append(f"# {title}")
        lines.append("")

    lines.append("```text")
    lines.append(ascii_table)
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def render_png(title: str | None, ascii_table: str, output_path: Path) -> None:
    lines = ascii_table.splitlines()
    line_count = len(lines) + (2 if title else 0)
    max_chars = max((len(line) for line in lines), default=0)

    figure_width = max(11.0, max_chars * 0.10)
    figure_height = max(4.0, line_count * 0.24)

    figure = plt.figure(figsize=(figure_width, figure_height))
    axis = figure.add_axes([0, 0, 1, 1])
    axis.axis("off")
    axis.set_facecolor("white")

    y_position = 0.98
    if title:
        axis.text(
            0.015,
            y_position,
            title,
            ha="left",
            va="top",
            family="monospace",
            fontsize=14,
            fontweight="bold",
        )
        y_position -= 0.07

    axis.text(
        0.015,
        y_position,
        ascii_table,
        ha="left",
        va="top",
        family="monospace",
        fontsize=10,
        linespacing=1.25,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output_path, dpi=200, bbox_inches="tight", pad_inches=0.18)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    output_png = args.output if args.output else args.input_csv.with_suffix(".png")
    output_md = args.markdown_output if args.markdown_output else args.input_csv.with_suffix(".md")

    case_id, rows = load_rows(args.input_csv)
    if not rows:
        raise SystemExit("No plottable rows were found in the CSV.")

    title = None if args.no_title else (args.title or "Calculated Table I")
    headers, table_rows, numeric_columns = build_table_matrix(group_rows(rows))
    ascii_table = build_ascii_table(headers, table_rows, numeric_columns)
    markdown_text = build_markdown_document(title, ascii_table)

    output_md.parent.mkdir(parents=True, exist_ok=True)
    output_md.write_text(markdown_text, encoding="utf-8")
    render_png(title, ascii_table, output_png)

    print(f"Wrote PNG table to {output_png}")
    print(f"Wrote Markdown table to {output_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
