#!/usr/bin/env python3

"""Plot Figure 7 nomogram lines from the CSVs generated by `reproduce_fig7`."""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the Figure 7 nomogram from reproduce_fig7 CSV outputs."
    )
    parser.add_argument("lines_csv", type=Path, help="Line-sample CSV generated by reproduce_fig7.")
    parser.add_argument(
        "--intersections-csv",
        type=Path,
        help="Optional intersections CSV to overlay the active-guide intersections.",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output image path. Defaults to the line CSV path with .png extension.",
    )
    parser.add_argument("--title", help="Optional title override.")
    return parser.parse_args()


def mode_label(row: dict[str, str]) -> str:
    superscript = "y" if row["mode_family"] == "E_y" else "x"
    return rf"$E^{{{superscript}}}_{{{row['p']}{row['q']}}}$"


def load_line_groups(lines_csv: Path) -> tuple[str, dict[tuple[str, str], list[dict[str, str]]]]:
    grouped: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)
    case_id = ""

    with lines_csv.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            case_id = row["case_id"]
            grouped[(row["line_kind"], row["line_id"])].append(row)

    for rows in grouped.values():
        rows.sort(key=lambda row: int(row["sample_index"]))

    return case_id, grouped


def load_reference_intersections(intersections_csv: Path | None) -> list[dict[str, str]]:
    if intersections_csv is None or not intersections_csv.exists():
        return []

    with intersections_csv.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        return [row for row in reader if row["is_reference_c"] == "1"]


def build_plot(
    case_id: str,
    grouped_lines: dict[tuple[str, str], list[dict[str, str]]],
    intersections: list[dict[str, str]],
    output_path: Path,
    title: str | None,
) -> None:
    plt.style.use("seaborn-v0_8-whitegrid")
    figure, axis = plt.subplots(figsize=(7.6, 7.2))

    for (line_kind, line_id), rows in grouped_lines.items():
        x_values = [float(row["x"]) for row in rows]
        y_values = [float(row["y"]) for row in rows]

        if line_kind == "mode":
            axis.plot(x_values, y_values, color="black", linewidth=1.7)
            label_row = rows[min(len(rows) - 1, max(1, len(rows) * 2 // 3))]
            axis.text(
                float(label_row["x"]) + 0.01,
                float(label_row["y"]) + 0.01,
                mode_label(label_row),
                fontsize=10,
            )
        else:
            axis.plot(x_values, y_values, color="black", linewidth=1.4, linestyle="--")
            label_row = rows[min(len(rows) - 1, max(1, len(rows) * 4 // 5))]
            axis.text(
                float(label_row["x"]) + 0.01,
                float(label_row["y"]) + 0.01,
                line_id.replace("C=", ""),
                fontsize=10,
            )

    if intersections:
        axis.scatter(
            [float(row["x"]) for row in intersections],
            [float(row["y"]) for row in intersections],
            color="#b22222",
            s=18,
            zorder=4,
        )

    axis.set_xlim(0.0, 1.0)
    axis.set_ylim(0.0, 1.0)
    axis.set_aspect("equal", adjustable="box")
    axis.set_xticks([index / 5 for index in range(6)])
    axis.set_yticks([index / 5 for index in range(6)])
    axis.set_xlabel(r"$X=\left(\frac{\pi}{a}\right)^2\left(1+\frac{A_3+A_5}{\pi a}\right)^{-2}(k_1^2-k_z^2)^{-1}$")
    axis.set_ylabel(r"$Y=\left(\frac{\pi}{b}\right)^2\left(1+\frac{n_2^2A_2+n_4^2A_4}{\pi n_1^2 b}\right)^{-2}(k_1^2-k_z^2)^{-1}$")
    axis.set_title(title or case_id)
    axis.grid(True, which="major", color="#d0d0d0", linewidth=0.8)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    figure.tight_layout()
    figure.savefig(output_path, dpi=200)
    plt.close(figure)


def main() -> int:
    args = parse_args()
    output_path = args.output if args.output else args.lines_csv.with_suffix(".png")

    case_id, grouped_lines = load_line_groups(args.lines_csv)
    intersections = load_reference_intersections(args.intersections_csv)
    build_plot(case_id, grouped_lines, intersections, output_path, args.title)
    print(f"Wrote plot to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
